import { Room, Booking, User, NotificationItem } from '../types';
import { getNext7Days } from '../utils/dateUtils';

export const DEMO_USER: User = {
  id: 'usr-vku-001',
  name: 'Nguyen Van Student',
  email: 'student@vku.edu.vn',
  studentId: '21IT001',
  role: 'student',
  major: 'Information Technology (VKU)',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
};

// 12+ Realistic VKU Rooms
export const INITIAL_ROOMS: Room[] = [
  // Building A
  {
    id: 'room-a101',
    name: 'A101 - Smart Study Haven',
    building: 'A',
    floor: 1,
    capacity: 6,
    type: 'Study Room',
    equipment: ['Whiteboard', 'AC'],
    currentOccupancy: 2,
    status: 'Available Now',
    description: 'A cozy natural light study room ideal for small peer groups and focused revision.',
    photo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-a203',
    name: 'A203 - Collaborative Seminar',
    building: 'A',
    floor: 2,
    capacity: 12,
    type: 'Discussion Room',
    equipment: ['Projector', 'Whiteboard', 'AC'],
    currentOccupancy: 8,
    status: 'Occupied',
    description: 'Equipped with dual whiteboards and high-lumen projection for team ideation and presentation.',
    photo: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-a305',
    name: 'A305 - Quiet Research Lounge',
    building: 'A',
    floor: 3,
    capacity: 4,
    type: 'Study Room',
    equipment: ['Whiteboard', 'AC'],
    currentOccupancy: 0,
    status: 'Available Now',
    description: 'A soundproof quiet space dedicated to individual thesis work and deep reading.',
    photo: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
  },

  // Building B
  {
    id: 'room-b102',
    name: 'B102 - Creative Discussion Lab',
    building: 'B',
    floor: 1,
    capacity: 10,
    type: 'Discussion Room',
    equipment: ['Projector', 'Whiteboard', 'AC'],
    currentOccupancy: 0,
    status: 'Available Now',
    description: 'Modular furniture layout supporting round-table debates and capstone project meetings.',
    photo: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-b204',
    name: 'B204 - Hardware & IoT Lab',
    building: 'B',
    floor: 2,
    capacity: 16,
    type: 'Computer Lab',
    equipment: ['High-spec PC', 'Projector', 'AC'],
    currentOccupancy: 14,
    status: 'Occupied',
    description: 'High performance testing benches for embedded systems and robotics student workshops.',
    photo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-b305',
    name: 'B305 - Network Architecture Lab',
    building: 'B',
    floor: 3,
    capacity: 18,
    type: 'Computer Lab',
    equipment: ['High-spec PC', 'Projector', 'AC'],
    currentOccupancy: 0,
    status: 'Maintenance',
    description: 'Undergoing Cisco switch firmware upgrades and network rack re-cabling.',
    photo: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
  },

  // Building C
  {
    id: 'room-c201',
    name: 'C201 - Executive Brainstorming',
    building: 'C',
    floor: 2,
    capacity: 8,
    type: 'Discussion Room',
    equipment: ['Whiteboard', 'Projector', 'AC'],
    currentOccupancy: 3,
    status: 'Available Now',
    description: 'Premium conference table with ergonomic chairs and full AV teleconference gear.',
    photo: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-c302',
    name: 'C302 - Software Engineering Hub',
    building: 'C',
    floor: 3,
    capacity: 20,
    type: 'Computer Lab',
    equipment: ['High-spec PC', 'Projector', 'Whiteboard', 'AC'],
    currentOccupancy: 18,
    status: 'Occupied',
    description: 'Dual-monitor workstations configured for cloud development and full-stack hackathons.',
    photo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-c405',
    name: 'C405 - Quiet Thesis Studio',
    building: 'C',
    floor: 4,
    capacity: 6,
    type: 'Study Room',
    equipment: ['Whiteboard', 'AC'],
    currentOccupancy: 0,
    status: 'Available Now',
    description: 'High floor tranquil workspace with panoramic campus views, perfect for finals prep.',
    photo: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
  },

  // Building V (VKU Tech Innovation Center)
  {
    id: 'room-v103',
    name: 'V103 - AI & Data Analytics Lab',
    building: 'V',
    floor: 1,
    capacity: 20,
    type: 'Computer Lab',
    equipment: ['High-spec PC', 'Projector', 'Whiteboard', 'AC'],
    currentOccupancy: 6,
    status: 'Available Now',
    description: 'State-of-the-art RTX-accelerated GPU workstations configured for Deep Learning training.',
    photo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-v203',
    name: 'V203 - Innovation Discussion Studio',
    building: 'V',
    floor: 2,
    capacity: 10,
    type: 'Discussion Room',
    equipment: ['Projector', 'Whiteboard', 'AC'],
    currentOccupancy: 4,
    status: 'Available Now',
    description: 'VKU innovation zone with touch interactive smart screen and writable glass partitions.',
    photo: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'room-v305',
    name: 'V305 - VR / Game Dev Lab',
    building: 'V',
    floor: 3,
    capacity: 15,
    type: 'Computer Lab',
    equipment: ['High-spec PC', 'Projector', 'AC'],
    currentOccupancy: 0,
    status: 'Maintenance',
    description: 'Undergoing sensor calibration and VR headset station firmware upgrades.',
    photo: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=800&q=80',
  },
];

// Helper to get dynamically generated dates for mock bookings
const days = getNext7Days();
const todayDate = days[0].dateString;
const tomorrowDate = days[1]?.dateString || todayDate;
const dayAfterDate = days[2]?.dateString || todayDate;

// 10+ Initial realistic bookings
export const INITIAL_BOOKINGS: Booking[] = [
  // Demo conflict scenario booking: V203 is pre-booked for tomorrow from 13:00 to 15:00
  {
    id: 'bk-vku-conflict-001',
    bookingCode: 'VKU-2026-V203CF',
    roomId: 'room-v203',
    roomName: 'V203 - Innovation Discussion Studio',
    building: 'V',
    floor: 2,
    roomType: 'Discussion Room',
    roomPhoto: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-999',
    userName: 'Le Thi Academic',
    userEmail: 'academic@vku.edu.vn',
    date: todayDate,
    startTime: '13:00',
    endTime: '15:00',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-V203CF:room-v203:13:00-15:00',
  },
  // Upcoming reservation for current demo user
  {
    id: 'bk-vku-002',
    bookingCode: 'VKU-2026-A101AB',
    roomId: 'room-a101',
    roomName: 'A101 - Smart Study Haven',
    building: 'A',
    floor: 1,
    roomType: 'Study Room',
    roomPhoto: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-001',
    userName: 'Nguyen Van Student',
    userEmail: 'student@vku.edu.vn',
    date: todayDate,
    startTime: '09:30',
    endTime: '11:30',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-A101AB:room-a101:09:30-11:30',
  },
  // Booking for user on tomorrow
  {
    id: 'bk-vku-003',
    bookingCode: 'VKU-2026-V103AI',
    roomId: 'room-v103',
    roomName: 'V103 - AI & Data Analytics Lab',
    building: 'V',
    floor: 1,
    roomType: 'Computer Lab',
    roomPhoto: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-001',
    userName: 'Nguyen Van Student',
    userEmail: 'student@vku.edu.vn',
    date: tomorrowDate,
    startTime: '07:30',
    endTime: '09:30',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-V103AI:room-v103:07:30-09:30',
  },
  // Other campus students bookings
  {
    id: 'bk-vku-004',
    bookingCode: 'VKU-2026-A203EX',
    roomId: 'room-a203',
    roomName: 'A203 - Collaborative Seminar',
    building: 'A',
    floor: 2,
    roomType: 'Discussion Room',
    roomPhoto: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-102',
    userName: 'Tran Minh Tri',
    userEmail: 'tritm@vku.edu.vn',
    date: todayDate,
    startTime: '07:30',
    endTime: '09:30',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-A203EX:room-a203:07:30-09:30',
  },
  {
    id: 'bk-vku-005',
    bookingCode: 'VKU-2026-B102CD',
    roomId: 'room-b102',
    roomName: 'B102 - Creative Discussion Lab',
    building: 'B',
    floor: 1,
    roomType: 'Discussion Room',
    roomPhoto: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-103',
    userName: 'Hoang Gia Bao',
    userEmail: 'baohg@vku.edu.vn',
    date: todayDate,
    startTime: '15:00',
    endTime: '17:00',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-B102CD:room-b102:15:00-17:00',
  },
  {
    id: 'bk-vku-006',
    bookingCode: 'VKU-2026-C201EB',
    roomId: 'room-c201',
    roomName: 'C201 - Executive Brainstorming',
    building: 'C',
    floor: 2,
    roomType: 'Discussion Room',
    roomPhoto: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-104',
    userName: 'Pham Thu Huong',
    userEmail: 'huongpt@vku.edu.vn',
    date: tomorrowDate,
    startTime: '09:30',
    endTime: '11:30',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-C201EB:room-c201:09:30-11:30',
  },
  {
    id: 'bk-vku-007',
    bookingCode: 'VKU-2026-C302SE',
    roomId: 'room-c302',
    roomName: 'C302 - Software Engineering Hub',
    building: 'C',
    floor: 3,
    roomType: 'Computer Lab',
    roomPhoto: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-105',
    userName: 'Doan Van Hau',
    userEmail: 'haudv@vku.edu.vn',
    date: tomorrowDate,
    startTime: '13:00',
    endTime: '15:00',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-C302SE:room-c302:13:00-15:00',
  },
  {
    id: 'bk-vku-008',
    bookingCode: 'VKU-2026-B204HW',
    roomId: 'room-b204',
    roomName: 'B204 - Hardware & IoT Lab',
    building: 'B',
    floor: 2,
    roomType: 'Computer Lab',
    roomPhoto: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-106',
    userName: 'Nguyen Ngoc Anh',
    userEmail: 'anhnn@vku.edu.vn',
    date: dayAfterDate,
    startTime: '07:30',
    endTime: '09:30',
    durationMinutes: 120,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    qrPayload: 'VKU-SPACEHUB:VKU-2026-B204HW:room-b204:07:30-09:30',
  },
  // User history items (completed and cancelled)
  {
    id: 'bk-vku-009',
    bookingCode: 'VKU-2026-C405HS',
    roomId: 'room-c405',
    roomName: 'C405 - Quiet Thesis Studio',
    building: 'C',
    floor: 4,
    roomType: 'Study Room',
    roomPhoto: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-001',
    userName: 'Nguyen Van Student',
    userEmail: 'student@vku.edu.vn',
    date: '2026-09-20',
    startTime: '13:00',
    endTime: '15:00',
    durationMinutes: 120,
    status: 'completed',
    createdAt: '2026-09-19T08:00:00.000Z',
    checkedInAt: '2026-09-20T12:55:00.000Z',
    qrPayload: 'VKU-SPACEHUB:VKU-2026-C405HS:room-c405:13:00-15:00',
  },
  {
    id: 'bk-vku-010',
    bookingCode: 'VKU-2026-A305CA',
    roomId: 'room-a305',
    roomName: 'A305 - Quiet Research Lounge',
    building: 'A',
    floor: 3,
    roomType: 'Study Room',
    roomPhoto: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    userId: 'usr-vku-001',
    userName: 'Nguyen Van Student',
    userEmail: 'student@vku.edu.vn',
    date: '2026-09-21',
    startTime: '15:00',
    endTime: '17:00',
    durationMinutes: 120,
    status: 'cancelled',
    createdAt: '2026-09-20T10:00:00.000Z',
    qrPayload: 'VKU-SPACEHUB:VKU-2026-A305CA:room-a305:15:00-17:00',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'booking_created',
    title: 'Reservation Confirmed',
    message: 'Your booking for A101 - Smart Study Haven has been confirmed.',
    timestamp: '2 hours ago',
    read: false,
    bookingId: 'bk-vku-002',
    bookingCode: 'VKU-2026-A101AB',
  },
  {
    id: 'notif-2',
    type: 'booking_reminder',
    title: 'Upcoming Session Reminder',
    message: 'Your study room reservation starts in 15 minutes at A101.',
    timestamp: '1 hour ago',
    read: false,
    bookingId: 'bk-vku-002',
    bookingCode: 'VKU-2026-A101AB',
  },
  {
    id: 'notif-3',
    type: 'check_in_success',
    title: 'Check-in Verified',
    message: 'You successfully checked in at C405 - Quiet Thesis Studio.',
    timestamp: '3 days ago',
    read: true,
    bookingId: 'bk-vku-009',
    bookingCode: 'VKU-2026-C405HS',
  },
];
